# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 361bc97b5c03e92c53e3f3cc35d2df2eb02aba5c257cb196e7aa0b1962047f2737bfbc8d9f141301b53b42b71d95ba10aa10779543c67a3033cf4385bff96c00

test:
  secret_key_base: 4294aa0a43f00c6d842c1ccec9c679260068a54397324a70f62df9adce2f855fb8b3c215713c0a8cbf22706aa5c689649319741994903daf0860dd16c1eb79a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
